/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocasEReembolsosRouteImport } from './routes/trocas-e-reembolsos'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PoliticaDeFreteRouteImport } from './routes/politica-de-frete'
import { Route as PagamentoSeguroRouteImport } from './routes/pagamento-seguro'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as DuvidasFrequentesRouteImport } from './routes/duvidas-frequentes'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AguardandoPagamentoRouteImport } from './routes/aguardando-pagamento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPaymentWebhookRouteImport } from './routes/api/public/payment-webhook'

const TrocasEReembolsosRoute = TrocasEReembolsosRouteImport.update({
  id: '/trocas-e-reembolsos',
  path: '/trocas-e-reembolsos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeFreteRoute = PoliticaDeFreteRouteImport.update({
  id: '/politica-de-frete',
  path: '/politica-de-frete',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoSeguroRoute = PagamentoSeguroRouteImport.update({
  id: '/pagamento-seguro',
  path: '/pagamento-seguro',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const DuvidasFrequentesRoute = DuvidasFrequentesRouteImport.update({
  id: '/duvidas-frequentes',
  path: '/duvidas-frequentes',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoPagamentoRoute = AguardandoPagamentoRouteImport.update({
  id: '/aguardando-pagamento',
  path: '/aguardando-pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentWebhookRoute = ApiPublicPaymentWebhookRouteImport.update({
  id: '/api/public/payment-webhook',
  path: '/api/public/payment-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aguardando-pagamento': typeof AguardandoPagamentoRoute
  '/checkout': typeof CheckoutRoute
  '/duvidas-frequentes': typeof DuvidasFrequentesRoute
  '/obrigado': typeof ObrigadoRoute
  '/pagamento-seguro': typeof PagamentoSeguroRoute
  '/politica-de-frete': typeof PoliticaDeFreteRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/trocas-e-reembolsos': typeof TrocasEReembolsosRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aguardando-pagamento': typeof AguardandoPagamentoRoute
  '/checkout': typeof CheckoutRoute
  '/duvidas-frequentes': typeof DuvidasFrequentesRoute
  '/obrigado': typeof ObrigadoRoute
  '/pagamento-seguro': typeof PagamentoSeguroRoute
  '/politica-de-frete': typeof PoliticaDeFreteRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/trocas-e-reembolsos': typeof TrocasEReembolsosRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aguardando-pagamento': typeof AguardandoPagamentoRoute
  '/checkout': typeof CheckoutRoute
  '/duvidas-frequentes': typeof DuvidasFrequentesRoute
  '/obrigado': typeof ObrigadoRoute
  '/pagamento-seguro': typeof PagamentoSeguroRoute
  '/politica-de-frete': typeof PoliticaDeFreteRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/trocas-e-reembolsos': typeof TrocasEReembolsosRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aguardando-pagamento'
    | '/checkout'
    | '/duvidas-frequentes'
    | '/obrigado'
    | '/pagamento-seguro'
    | '/politica-de-frete'
    | '/politica-de-privacidade'
    | '/quem-somos'
    | '/termos-de-uso'
    | '/trocas-e-reembolsos'
    | '/api/public/payment-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aguardando-pagamento'
    | '/checkout'
    | '/duvidas-frequentes'
    | '/obrigado'
    | '/pagamento-seguro'
    | '/politica-de-frete'
    | '/politica-de-privacidade'
    | '/quem-somos'
    | '/termos-de-uso'
    | '/trocas-e-reembolsos'
    | '/api/public/payment-webhook'
  id:
    | '__root__'
    | '/'
    | '/aguardando-pagamento'
    | '/checkout'
    | '/duvidas-frequentes'
    | '/obrigado'
    | '/pagamento-seguro'
    | '/politica-de-frete'
    | '/politica-de-privacidade'
    | '/quem-somos'
    | '/termos-de-uso'
    | '/trocas-e-reembolsos'
    | '/api/public/payment-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AguardandoPagamentoRoute: typeof AguardandoPagamentoRoute
  CheckoutRoute: typeof CheckoutRoute
  DuvidasFrequentesRoute: typeof DuvidasFrequentesRoute
  ObrigadoRoute: typeof ObrigadoRoute
  PagamentoSeguroRoute: typeof PagamentoSeguroRoute
  PoliticaDeFreteRoute: typeof PoliticaDeFreteRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  QuemSomosRoute: typeof QuemSomosRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  TrocasEReembolsosRoute: typeof TrocasEReembolsosRoute
  ApiPublicPaymentWebhookRoute: typeof ApiPublicPaymentWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocas-e-reembolsos': {
      id: '/trocas-e-reembolsos'
      path: '/trocas-e-reembolsos'
      fullPath: '/trocas-e-reembolsos'
      preLoaderRoute: typeof TrocasEReembolsosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-frete': {
      id: '/politica-de-frete'
      path: '/politica-de-frete'
      fullPath: '/politica-de-frete'
      preLoaderRoute: typeof PoliticaDeFreteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento-seguro': {
      id: '/pagamento-seguro'
      path: '/pagamento-seguro'
      fullPath: '/pagamento-seguro'
      preLoaderRoute: typeof PagamentoSeguroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duvidas-frequentes': {
      id: '/duvidas-frequentes'
      path: '/duvidas-frequentes'
      fullPath: '/duvidas-frequentes'
      preLoaderRoute: typeof DuvidasFrequentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando-pagamento': {
      id: '/aguardando-pagamento'
      path: '/aguardando-pagamento'
      fullPath: '/aguardando-pagamento'
      preLoaderRoute: typeof AguardandoPagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payment-webhook': {
      id: '/api/public/payment-webhook'
      path: '/api/public/payment-webhook'
      fullPath: '/api/public/payment-webhook'
      preLoaderRoute: typeof ApiPublicPaymentWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AguardandoPagamentoRoute: AguardandoPagamentoRoute,
  CheckoutRoute: CheckoutRoute,
  DuvidasFrequentesRoute: DuvidasFrequentesRoute,
  ObrigadoRoute: ObrigadoRoute,
  PagamentoSeguroRoute: PagamentoSeguroRoute,
  PoliticaDeFreteRoute: PoliticaDeFreteRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  QuemSomosRoute: QuemSomosRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  TrocasEReembolsosRoute: TrocasEReembolsosRoute,
  ApiPublicPaymentWebhookRoute: ApiPublicPaymentWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
